name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Simple tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare the Node environment
        uses: ./.github/actions/prepare_node

      - name: Test
        run: npm test
